import type { City, MatatuRoute } from './types';

export const CITIES: City[] = [
  {
    id: 'nairobi',
    name: 'Nairobi',
    county: 'Nairobi County',
    tagline: 'The home of nganya culture',
    description:
      'Over 20,000 matatus work the capital. Routes are numbered and radiate from the CBD termini at Kencom, Railways, Odeon and Ambassadeur.',
    mainTerminus: 'Kencom / Railways',
    latitude: -1.2864,
    longitude: 36.8272,
  },
  {
    id: 'mombasa',
    name: 'Mombasa',
    county: 'Mombasa County',
    tagline: 'Island routes and the Likoni ferry',
    description:
      'Coastal routes hinge on the causeways and the Likoni ferry. Tuk tuks feed the matatu stages around Mwembe Tayari and Buxton.',
    mainTerminus: 'Mwembe Tayari',
    latitude: -4.053,
    longitude: 39.669,
  },
  {
    id: 'kisumu',
    name: 'Kisumu',
    county: 'Kisumu County',
    tagline: 'Lakeside stages and boda links',
    description:
      'Most routes start at the Kisumu bus park and fan out through Kondele, Manyatta and Nyalenda before reaching the lake road.',
    mainTerminus: 'Kisumu Bus Park',
    latitude: -0.0917,
    longitude: 34.768,
  },
  {
    id: 'nakuru',
    name: 'Nakuru',
    county: 'Nakuru County',
    tagline: 'Rift Valley city hops',
    description:
      'Short, cheap town routes connect the CBD with Kaptembwo, Free Area, Lanet and Pipeline, with 14-seaters dominating.',
    mainTerminus: 'Nakuru CBD Stage',
    latitude: -0.283,
    longitude: 36.066,
  },
  {
    id: 'eldoret',
    name: 'Eldoret',
    county: 'Uasin Gishu County',
    tagline: 'Compact routes across the highlands',
    description:
      'Eldoret town routes are quick and flat-fare, running from the Uganda Road stages out to Langas, Huruma, Kapsoya and Annex.',
    mainTerminus: 'Uganda Road Stage',
    latitude: 0.5143,
    longitude: 35.2698,
  },
  {
    id: 'thika',
    name: 'Thika',
    county: 'Kiambu County',
    tagline: 'Superhighway commuter belt',
    description:
      'Local Thika routes feed the town estates while the Nairobi corridor along Thika Superhighway carries heavy commuter traffic.',
    mainTerminus: 'Thika Town Stage',
    latitude: -1.0388,
    longitude: 37.0834,
  },
  {
    id: 'nyeri',
    name: 'Nyeri',
    county: 'Nyeri County',
    tagline: 'Aberdare foothill stages',
    description:
      'Nyeri routes are short and frequent, serving Kamakwa, Kingongo, Ruringu and the Mweiga road up towards the Aberdares.',
    mainTerminus: 'Nyeri Town Stage',
    latitude: -0.42,
    longitude: 36.9476,
  },
  {
    id: 'machakos',
    name: 'Machakos',
    county: 'Machakos County',
    tagline: 'Ukambani hills and Mombasa Road',
    description:
      'Town routes cover Mumbuni and Katoloni while longer runs drop down to Athi River, Kyumbi and the Mombasa Road junctions.',
    mainTerminus: 'Machakos Town Stage',
    latitude: -1.5177,
    longitude: 37.2634,
  },
];

export const ROUTES: MatatuRoute[] = [
  // ---------------------------------------------------------------- Nairobi
  {
    id: 'nairobi-46',
    cityId: 'nairobi',
    number: '46',
    from: 'Kencom (CBD)',
    to: 'Kawangware 46',
    corridor: 'Ngong Road',
    saccos: ['Super Metro', 'Kawangware Matatu Sacco', 'Latema Travellers'],
    vehicle: 'Nganya (14-seater)',
    distanceKm: 11.4,
    durationMin: 40,
    operatingHours: '04:45 – 23:30',
    frequencyMin: 3,
    offPeakFare: { min: 50, max: 70 },
    peakFare: { min: 100, max: 150 },
    color: '#16a34a',
    notes: 'Loudest sound systems in the city. Fares spike sharply when it rains on Ngong Road.',
    stages: [
      { name: 'Kencom', latitude: -1.2857, longitude: 36.8244, landmark: 'City Hall Way' },
      { name: 'Nairobi Hospital', latitude: -1.2977, longitude: 36.8083, landmark: 'Argwings Kodhek' },
      { name: 'Adams Arcade', latitude: -1.2977, longitude: 36.7783 },
      { name: 'Racecourse', latitude: -1.301, longitude: 36.762, landmark: 'Ngong Racecourse' },
      { name: 'Dagoretti Corner', latitude: -1.2985, longitude: 36.7443 },
      { name: 'Kawangware 46', latitude: -1.286, longitude: 36.744, landmark: 'Stage 46' },
    ],
  },
  {
    id: 'nairobi-44',
    cityId: 'nairobi',
    number: '44',
    from: 'Kencom (CBD)',
    to: 'Kangemi',
    corridor: 'Waiyaki Way',
    saccos: ['Super Metro', 'Kangemi Nyathi', 'Compliant Shuttle'],
    vehicle: '14-seater matatu',
    distanceKm: 10.8,
    durationMin: 35,
    operatingHours: '04:30 – 23:00',
    frequencyMin: 2,
    offPeakFare: { min: 50, max: 80 },
    peakFare: { min: 100, max: 150 },
    color: '#0ea5e9',
    notes: 'Expressway traffic pushes evening fares up. Super Metro keeps a flat card fare.',
    stages: [
      { name: 'Kencom', latitude: -1.2857, longitude: 36.8244 },
      { name: 'Museum Hill', latitude: -1.274, longitude: 36.8155 },
      { name: 'Westlands', latitude: -1.2673, longitude: 36.8065, landmark: 'Sarit Centre' },
      { name: 'ABC Place', latitude: -1.2646, longitude: 36.7907 },
      { name: 'Mountain View', latitude: -1.2655, longitude: 36.7625 },
      { name: 'Kangemi', latitude: -1.2662, longitude: 36.7429, landmark: 'Kangemi Market' },
    ],
  },
  {
    id: 'nairobi-111',
    cityId: 'nairobi',
    number: '111',
    from: 'Railways (CBD)',
    to: 'Ngong Town',
    corridor: 'Ngong Road / Karen',
    saccos: ['Ngong Forest Sacco', 'Kerarapon Shuttle', 'ROG Sacco'],
    vehicle: '14-seater matatu',
    distanceKm: 24.6,
    durationMin: 65,
    operatingHours: '05:00 – 22:30',
    frequencyMin: 6,
    offPeakFare: { min: 80, max: 100 },
    peakFare: { min: 150, max: 200 },
    color: '#7c3aed',
    notes: 'Boarding at Karen Shopping Centre is cheaper than boarding in town after 17:00.',
    stages: [
      { name: 'Railways', latitude: -1.2864, longitude: 36.8272, landmark: 'Railways Terminus' },
      { name: 'The Junction', latitude: -1.3007, longitude: 36.7635 },
      { name: 'Dagoretti Corner', latitude: -1.2985, longitude: 36.7443 },
      { name: 'Karen Shopping Centre', latitude: -1.3197, longitude: 36.7076 },
      { name: 'Kerarapon', latitude: -1.341, longitude: 36.687 },
      { name: 'Ngong Town', latitude: -1.3596, longitude: 36.657, landmark: 'Ngong Market' },
    ],
  },
  {
    id: 'nairobi-58',
    cityId: 'nairobi',
    number: '58',
    from: 'Ambassadeur (CBD)',
    to: 'Umoja 1',
    corridor: 'Jogoo Road',
    saccos: ['Umoinner', 'Embassava', 'Forward Travellers'],
    vehicle: 'Nganya (14-seater)',
    distanceKm: 12.2,
    durationMin: 45,
    operatingHours: '04:30 – 00:30',
    frequencyMin: 2,
    offPeakFare: { min: 50, max: 70 },
    peakFare: { min: 100, max: 130 },
    color: '#f97316',
    notes: 'Embassava and Umoinner nganyas run the loudest Jogoo Road fleet. Very busy at 06:00.',
    stages: [
      { name: 'Ambassadeur', latitude: -1.2833, longitude: 36.8265 },
      { name: 'City Stadium', latitude: -1.2925, longitude: 36.842 },
      { name: 'Makadara', latitude: -1.2966, longitude: 36.862, landmark: 'Makadara Law Courts' },
      { name: 'Buruburu', latitude: -1.287, longitude: 36.888, landmark: 'Buruburu Shopping Centre' },
      { name: 'Umoja 1', latitude: -1.2793, longitude: 36.893 },
    ],
  },
  {
    id: 'nairobi-33',
    cityId: 'nairobi',
    number: '33',
    from: 'Railways (CBD)',
    to: 'JKIA',
    corridor: 'Mombasa Road / Airport North Road',
    saccos: ['City Shuttle', 'Embakasi Sacco', 'Kenya Mpya'],
    vehicle: '33-seater bus',
    distanceKm: 18.5,
    durationMin: 55,
    operatingHours: '04:00 – 23:00',
    frequencyMin: 8,
    offPeakFare: { min: 60, max: 80 },
    peakFare: { min: 100, max: 150 },
    color: '#dc2626',
    notes: 'The cheapest way to the airport. Allow extra time for the Cabanas jam.',
    stages: [
      { name: 'Railways', latitude: -1.2864, longitude: 36.8272 },
      { name: 'Nyayo Stadium', latitude: -1.306, longitude: 36.829 },
      { name: 'Cabanas', latitude: -1.332, longitude: 36.883 },
      { name: 'Embakasi Village', latitude: -1.3167, longitude: 36.9 },
      { name: 'JKIA Terminal 1', latitude: -1.3192, longitude: 36.9278 },
    ],
  },
  {
    id: 'nairobi-125',
    cityId: 'nairobi',
    number: '125',
    from: 'Railways (CBD)',
    to: 'Ongata Rongai',
    corridor: 'Langata Road',
    saccos: ['Rongai Kenya Mpya', 'Lopha Travellers', 'Kagemi Sacco'],
    vehicle: '51-seater bus',
    distanceKm: 22.1,
    durationMin: 60,
    operatingHours: '04:30 – 23:30',
    frequencyMin: 4,
    offPeakFare: { min: 70, max: 100 },
    peakFare: { min: 150, max: 250 },
    color: '#0891b2',
    notes: 'Rongai buses are famous for their graffiti and screens. Rain doubles the evening fare.',
    stages: [
      { name: 'Railways', latitude: -1.2864, longitude: 36.8272 },
      { name: 'Wilson Airport', latitude: -1.3222, longitude: 36.8148 },
      { name: 'Bomas of Kenya', latitude: -1.3396, longitude: 36.7621 },
      { name: 'Galleria', latitude: -1.346, longitude: 36.749 },
      { name: 'Tuskys Rongai', latitude: -1.3888, longitude: 36.7502 },
      { name: 'Ongata Rongai', latitude: -1.397, longitude: 36.744 },
    ],
  },
  {
    id: 'nairobi-145',
    cityId: 'nairobi',
    number: '145',
    from: 'Odeon (CBD)',
    to: 'Githurai 45',
    corridor: 'Thika Superhighway',
    saccos: ['Githurai 45 Sacco', 'Kenya Mpya', 'Star Bus'],
    vehicle: '33-seater bus',
    distanceKm: 17.8,
    durationMin: 50,
    operatingHours: '04:00 – 00:00',
    frequencyMin: 2,
    offPeakFare: { min: 60, max: 80 },
    peakFare: { min: 120, max: 180 },
    color: '#facc15',
    notes: 'One of the busiest corridors in Kenya. Buses fill up in minutes at Odeon after 17:30.',
    stages: [
      { name: 'Odeon', latitude: -1.2822, longitude: 36.8215 },
      { name: 'Pangani', latitude: -1.2695, longitude: 36.8348 },
      { name: 'Allsops', latitude: -1.245, longitude: 36.872 },
      { name: 'Roysambu', latitude: -1.22, longitude: 36.888, landmark: 'TRM' },
      { name: 'Kahawa Sukari', latitude: -1.1985, longitude: 36.9155 },
      { name: 'Githurai 45', latitude: -1.193, longitude: 36.92 },
    ],
  },
  {
    id: 'nairobi-17b',
    cityId: 'nairobi',
    number: '17B',
    from: 'Kencom (CBD)',
    to: 'Lavington',
    corridor: 'Kileleshwa / Lavington',
    saccos: ['Kileleshwa Sacco', 'Metro Trans'],
    vehicle: '14-seater matatu',
    distanceKm: 9.2,
    durationMin: 35,
    operatingHours: '05:30 – 22:00',
    frequencyMin: 7,
    offPeakFare: { min: 50, max: 70 },
    peakFare: { min: 80, max: 120 },
    color: '#db2777',
    notes: 'Quieter, low-volume route. Service thins out considerably on Sundays.',
    stages: [
      { name: 'Kencom', latitude: -1.2857, longitude: 36.8244 },
      { name: 'Yaya Centre', latitude: -1.293, longitude: 36.783 },
      { name: 'Kileleshwa', latitude: -1.28, longitude: 36.777, landmark: 'Oloitokitok Road' },
      { name: 'Valley Arcade', latitude: -1.29, longitude: 36.766 },
      { name: 'Lavington Mall', latitude: -1.279, longitude: 36.764 },
    ],
  },
  {
    id: 'nairobi-32',
    cityId: 'nairobi',
    number: '32',
    from: 'Odeon (CBD)',
    to: 'Kayole Junction',
    corridor: 'Juja Road / Outer Ring',
    saccos: ['Kayole Travellers', 'Umoinner', 'Nairobi East Sacco'],
    vehicle: 'Nganya (14-seater)',
    distanceKm: 14.6,
    durationMin: 50,
    operatingHours: '04:30 – 00:00',
    frequencyMin: 3,
    offPeakFare: { min: 50, max: 80 },
    peakFare: { min: 100, max: 150 },
    color: '#4f46e5',
    notes: 'Outer Ring Road roadworks and the Kariobangi jam are the usual delay points.',
    stages: [
      { name: 'Odeon', latitude: -1.2822, longitude: 36.8215 },
      { name: 'Ngara', latitude: -1.276, longitude: 36.827 },
      { name: 'Eastleigh Section 3', latitude: -1.274, longitude: 36.848 },
      { name: 'Kariobangi', latitude: -1.253, longitude: 36.879 },
      { name: 'Kayole Junction', latitude: -1.2731, longitude: 36.9147 },
    ],
  },
  {
    id: 'nairobi-8c',
    cityId: 'nairobi',
    number: '8C',
    from: 'Railways (CBD)',
    to: 'South C',
    corridor: 'Lusaka Road / South B',
    saccos: ['South B Sacco', 'City Hoppa'],
    vehicle: '25-seater matatu',
    distanceKm: 7.4,
    durationMin: 28,
    operatingHours: '05:00 – 22:30',
    frequencyMin: 5,
    offPeakFare: { min: 40, max: 60 },
    peakFare: { min: 70, max: 100 },
    color: '#059669',
    notes: 'Short hop route. Mater Hospital is the busiest mid-route stage.',
    stages: [
      { name: 'Railways', latitude: -1.2864, longitude: 36.8272 },
      { name: 'Nyayo Stadium', latitude: -1.306, longitude: 36.829 },
      { name: 'South B Shopping', latitude: -1.311, longitude: 36.8365 },
      { name: 'Mater Hospital', latitude: -1.307, longitude: 36.832 },
      { name: 'South C', latitude: -1.321, longitude: 36.8296, landmark: 'Shopping Centre' },
    ],
  },

  // ---------------------------------------------------------------- Mombasa
  {
    id: 'mombasa-5',
    cityId: 'mombasa',
    number: '5',
    from: 'Mwembe Tayari',
    to: 'Likoni',
    corridor: 'Likoni Ferry',
    saccos: ['Likoni Matatu Sacco', 'Coast Bus Shuttle'],
    vehicle: '14-seater matatu',
    distanceKm: 6.8,
    durationMin: 35,
    operatingHours: '05:00 – 23:00',
    frequencyMin: 3,
    offPeakFare: { min: 40, max: 60 },
    peakFare: { min: 70, max: 100 },
    color: '#0ea5e9',
    notes: 'Journey time depends entirely on the ferry queue. Passengers cross on foot at peak.',
    stages: [
      { name: 'Mwembe Tayari', latitude: -4.053, longitude: 39.669 },
      { name: 'Buxton', latitude: -4.048, longitude: 39.666 },
      { name: 'Likoni Ferry (Island)', latitude: -4.0668, longitude: 39.662 },
      { name: 'Likoni Ferry (Mainland)', latitude: -4.079, longitude: 39.66 },
      { name: 'Likoni Stage', latitude: -4.087, longitude: 39.66 },
    ],
  },
  {
    id: 'mombasa-8',
    cityId: 'mombasa',
    number: '8',
    from: 'Mombasa CBD',
    to: 'Mtwapa',
    corridor: 'Malindi Road',
    saccos: ['Mtwapa Sacco', 'Nyali Coast Shuttle', 'Kenya Coast Bus'],
    vehicle: '33-seater bus',
    distanceKm: 21.4,
    durationMin: 55,
    operatingHours: '05:00 – 00:00',
    frequencyMin: 5,
    offPeakFare: { min: 60, max: 90 },
    peakFare: { min: 100, max: 150 },
    color: '#16a34a',
    notes: 'The Mtwapa creek bridge is the main bottleneck on Friday evenings.',
    stages: [
      { name: 'Mombasa CBD', latitude: -4.053, longitude: 39.669 },
      { name: 'Nyali Bridge', latitude: -4.043, longitude: 39.688 },
      { name: 'City Mall Nyali', latitude: -4.04, longitude: 39.705 },
      { name: 'Bamburi', latitude: -3.99, longitude: 39.728 },
      { name: 'Shanzu', latitude: -3.98, longitude: 39.735 },
      { name: 'Mtwapa', latitude: -3.945, longitude: 39.744 },
    ],
  },
  {
    id: 'mombasa-11',
    cityId: 'mombasa',
    number: '11',
    from: 'Mombasa CBD',
    to: 'Kisauni',
    corridor: 'Kisauni / Bombolulu',
    saccos: ['Kisauni Sacco', 'Bombolulu Shuttle'],
    vehicle: '14-seater matatu',
    distanceKm: 8.6,
    durationMin: 30,
    operatingHours: '05:00 – 23:00',
    frequencyMin: 4,
    offPeakFare: { min: 40, max: 60 },
    peakFare: { min: 70, max: 100 },
    color: '#f97316',
    notes: 'Tuk tuks fill in the last mile to the interior Kisauni estates.',
    stages: [
      { name: 'Mombasa CBD', latitude: -4.053, longitude: 39.669 },
      { name: 'Nyali Bridge', latitude: -4.043, longitude: 39.688 },
      { name: 'Bombolulu', latitude: -4.018, longitude: 39.706 },
      { name: 'Kisauni Junction', latitude: -4.027, longitude: 39.695 },
    ],
  },
  {
    id: 'mombasa-3',
    cityId: 'mombasa',
    number: '3',
    from: 'Mombasa CBD',
    to: 'Port Reitz',
    corridor: 'Changamwe / Magongo',
    saccos: ['Changamwe Sacco', 'Port Reitz Shuttle'],
    vehicle: '14-seater matatu',
    distanceKm: 10.2,
    durationMin: 35,
    operatingHours: '04:45 – 22:30',
    frequencyMin: 4,
    offPeakFare: { min: 40, max: 60 },
    peakFare: { min: 70, max: 100 },
    color: '#7c3aed',
    notes: 'Serves the port and refinery shifts, so it is busy at 06:00, 14:00 and 22:00.',
    stages: [
      { name: 'Mombasa CBD', latitude: -4.053, longitude: 39.669 },
      { name: 'Makupa', latitude: -4.045, longitude: 39.657 },
      { name: 'Magongo', latitude: -4.018, longitude: 39.618 },
      { name: 'Changamwe', latitude: -4.027, longitude: 39.611 },
      { name: 'Port Reitz', latitude: -4.033, longitude: 39.612 },
    ],
  },
  {
    id: 'mombasa-10',
    cityId: 'mombasa',
    number: '10',
    from: 'Mombasa CBD',
    to: 'Miritini',
    corridor: 'Nairobi Highway',
    saccos: ['Miritini Sacco', 'Mikindani Travellers'],
    vehicle: '25-seater matatu',
    distanceKm: 14.8,
    durationMin: 40,
    operatingHours: '05:00 – 22:00',
    frequencyMin: 6,
    offPeakFare: { min: 50, max: 70 },
    peakFare: { min: 80, max: 120 },
    color: '#dc2626',
    notes: 'Connects with the SGR terminus shuttles at Miritini.',
    stages: [
      { name: 'Mombasa CBD', latitude: -4.053, longitude: 39.669 },
      { name: 'Makupa', latitude: -4.045, longitude: 39.657 },
      { name: 'Mikindani', latitude: -4.0, longitude: 39.596 },
      { name: 'Miritini', latitude: -3.988, longitude: 39.581, landmark: 'SGR Terminus' },
    ],
  },
  {
    id: 'mombasa-15',
    cityId: 'mombasa',
    number: '15',
    from: 'Mwembe Tayari',
    to: 'Old Town',
    corridor: 'Tudor / Kibokoni',
    saccos: ['Tudor Sacco', 'Old Town Tuk Tuk Association'],
    vehicle: 'Tuk tuk & matatu',
    distanceKm: 5.1,
    durationMin: 22,
    operatingHours: '06:00 – 21:00',
    frequencyMin: 8,
    offPeakFare: { min: 30, max: 50 },
    peakFare: { min: 50, max: 80 },
    color: '#0891b2',
    notes: 'Narrow Old Town lanes mean tuk tuks handle the final stages.',
    stages: [
      { name: 'Mwembe Tayari', latitude: -4.053, longitude: 39.669 },
      { name: 'Tudor', latitude: -4.041, longitude: 39.656 },
      { name: 'Buxton', latitude: -4.048, longitude: 39.666 },
      { name: 'Kibokoni (Old Town)', latitude: -4.062, longitude: 39.674, landmark: 'Fort Jesus' },
    ],
  },

  // ---------------------------------------------------------------- Kisumu
  {
    id: 'kisumu-7',
    cityId: 'kisumu',
    number: '7',
    from: 'Kisumu Bus Park',
    to: 'Mamboleo',
    corridor: 'Kondele / Kakamega Road',
    saccos: ['Kondele Sacco', 'Mamboleo Travellers'],
    vehicle: '14-seater matatu',
    distanceKm: 7.6,
    durationMin: 25,
    operatingHours: '05:30 – 22:00',
    frequencyMin: 4,
    offPeakFare: { min: 40, max: 60 },
    peakFare: { min: 70, max: 100 },
    color: '#16a34a',
    notes: 'Kondele roundabout is the busiest transfer point in the city.',
    stages: [
      { name: 'Kisumu Bus Park', latitude: -0.0917, longitude: 34.768 },
      { name: 'Kibuye Market', latitude: -0.0995, longitude: 34.762 },
      { name: 'Kondele', latitude: -0.074, longitude: 34.777 },
      { name: 'Mamboleo', latitude: -0.053, longitude: 34.781 },
    ],
  },
  {
    id: 'kisumu-9',
    cityId: 'kisumu',
    number: '9',
    from: 'Kisumu Bus Park',
    to: 'Dunga Beach',
    corridor: 'Nyalenda / Lake Road',
    saccos: ['Nyalenda Sacco', 'Dunga Shuttle'],
    vehicle: '14-seater matatu',
    distanceKm: 6.4,
    durationMin: 24,
    operatingHours: '06:00 – 21:00',
    frequencyMin: 7,
    offPeakFare: { min: 40, max: 50 },
    peakFare: { min: 60, max: 80 },
    color: '#0ea5e9',
    notes: 'Popular in the evening for the Dunga fish market. Thins out after dark.',
    stages: [
      { name: 'Kisumu Bus Park', latitude: -0.0917, longitude: 34.768 },
      { name: 'Jubilee Market', latitude: -0.098, longitude: 34.755 },
      { name: 'Nyalenda', latitude: -0.113, longitude: 34.762 },
      { name: 'Dunga Beach', latitude: -0.121, longitude: 34.742 },
    ],
  },
  {
    id: 'kisumu-11',
    cityId: 'kisumu',
    number: '11',
    from: 'Kisumu Bus Park',
    to: 'Manyatta',
    corridor: 'Manyatta',
    saccos: ['Manyatta Sacco'],
    vehicle: '14-seater matatu',
    distanceKm: 5.2,
    durationMin: 20,
    operatingHours: '05:30 – 22:30',
    frequencyMin: 3,
    offPeakFare: { min: 30, max: 50 },
    peakFare: { min: 60, max: 80 },
    color: '#f97316',
    notes: 'The densest residential route in Kisumu, so vehicles fill fast at 07:00.',
    stages: [
      { name: 'Kisumu Bus Park', latitude: -0.0917, longitude: 34.768 },
      { name: 'Kondele', latitude: -0.074, longitude: 34.777 },
      { name: 'Manyatta', latitude: -0.085, longitude: 34.783 },
    ],
  },
  {
    id: 'kisumu-3',
    cityId: 'kisumu',
    number: '3',
    from: 'Kisumu Bus Park',
    to: 'Ahero',
    corridor: 'Nairobi Road',
    saccos: ['Ahero Sacco', 'Nyamasaria Travellers'],
    vehicle: '25-seater matatu',
    distanceKm: 22.5,
    durationMin: 45,
    operatingHours: '05:00 – 21:00',
    frequencyMin: 10,
    offPeakFare: { min: 80, max: 100 },
    peakFare: { min: 120, max: 160 },
    color: '#7c3aed',
    notes: 'Long-haul town exit route serving the Kano plains rice schemes.',
    stages: [
      { name: 'Kisumu Bus Park', latitude: -0.0917, longitude: 34.768 },
      { name: 'Nyamasaria', latitude: -0.109, longitude: 34.797 },
      { name: 'Kajulu', latitude: -0.135, longitude: 34.86 },
      { name: 'Ahero', latitude: -0.172, longitude: 34.92 },
    ],
  },
  {
    id: 'kisumu-21',
    cityId: 'kisumu',
    number: '21',
    from: 'Kisumu Bus Park',
    to: 'Otonglo',
    corridor: 'Busia Road',
    saccos: ['Otonglo Sacco', 'Bandani Shuttle'],
    vehicle: '14-seater matatu',
    distanceKm: 8.1,
    durationMin: 26,
    operatingHours: '05:30 – 21:30',
    frequencyMin: 6,
    offPeakFare: { min: 40, max: 60 },
    peakFare: { min: 70, max: 90 },
    color: '#db2777',
    notes: 'Shares the Busia Road corridor with heavy trucks heading to the border.',
    stages: [
      { name: 'Kisumu Bus Park', latitude: -0.0917, longitude: 34.768 },
      { name: 'Bandani', latitude: -0.094, longitude: 34.729 },
      { name: 'Otonglo', latitude: -0.09, longitude: 34.71 },
    ],
  },

  // ---------------------------------------------------------------- Nakuru
  {
    id: 'nakuru-1',
    cityId: 'nakuru',
    number: '1',
    from: 'Nakuru CBD',
    to: 'Kaptembwo',
    corridor: 'Kaptembwo / Rhonda',
    saccos: ['Kaptembwo Sacco', 'Rhonda Travellers'],
    vehicle: '14-seater matatu',
    distanceKm: 4.8,
    durationMin: 18,
    operatingHours: '05:30 – 22:30',
    frequencyMin: 3,
    offPeakFare: { min: 30, max: 50 },
    peakFare: { min: 50, max: 80 },
    color: '#16a34a',
    notes: 'Highest-volume estate route in Nakuru with near-continuous departures.',
    stages: [
      { name: 'Nakuru CBD', latitude: -0.283, longitude: 36.066 },
      { name: 'London', latitude: -0.289, longitude: 36.053 },
      { name: 'Rhonda', latitude: -0.301, longitude: 36.047 },
      { name: 'Kaptembwo', latitude: -0.296, longitude: 36.041 },
    ],
  },
  {
    id: 'nakuru-4',
    cityId: 'nakuru',
    number: '4',
    from: 'Nakuru CBD',
    to: 'Kiti',
    corridor: 'Free Area',
    saccos: ['Free Area Sacco', 'Kiti Shuttle'],
    vehicle: '14-seater matatu',
    distanceKm: 6.5,
    durationMin: 22,
    operatingHours: '05:30 – 22:00',
    frequencyMin: 5,
    offPeakFare: { min: 30, max: 50 },
    peakFare: { min: 60, max: 80 },
    color: '#0ea5e9',
    notes: 'Free Area market days slow the middle section of the route.',
    stages: [
      { name: 'Nakuru CBD', latitude: -0.283, longitude: 36.066 },
      { name: 'Shabab', latitude: -0.29, longitude: 36.076 },
      { name: 'Free Area', latitude: -0.271, longitude: 36.09 },
      { name: 'Kiti', latitude: -0.262, longitude: 36.1 },
    ],
  },
  {
    id: 'nakuru-6',
    cityId: 'nakuru',
    number: '6',
    from: 'Nakuru CBD',
    to: 'Lanet',
    corridor: 'Nairobi Highway',
    saccos: ['Lanet Sacco', 'Pipeline Travellers'],
    vehicle: '25-seater matatu',
    distanceKm: 9.4,
    durationMin: 28,
    operatingHours: '05:00 – 22:30',
    frequencyMin: 6,
    offPeakFare: { min: 40, max: 60 },
    peakFare: { min: 70, max: 100 },
    color: '#f97316',
    notes: 'Runs along the highway, so it is quick outside the morning peak.',
    stages: [
      { name: 'Nakuru CBD', latitude: -0.283, longitude: 36.066 },
      { name: 'Naka', latitude: -0.302, longitude: 36.065 },
      { name: 'Pipeline', latitude: -0.323, longitude: 36.077 },
      { name: 'Lanet', latitude: -0.304, longitude: 36.13 },
    ],
  },
  {
    id: 'nakuru-9',
    cityId: 'nakuru',
    number: '9',
    from: 'Nakuru CBD',
    to: 'Bahati',
    corridor: 'Bahati Road',
    saccos: ['Bahati Sacco'],
    vehicle: '14-seater matatu',
    distanceKm: 13.2,
    durationMin: 35,
    operatingHours: '05:30 – 21:00',
    frequencyMin: 9,
    offPeakFare: { min: 50, max: 70 },
    peakFare: { min: 80, max: 120 },
    color: '#7c3aed',
    notes: 'Climbs out of the Rift towards the Bahati highlands farms.',
    stages: [
      { name: 'Nakuru CBD', latitude: -0.283, longitude: 36.066 },
      { name: 'Free Area', latitude: -0.271, longitude: 36.09 },
      { name: 'Kabatini', latitude: -0.222, longitude: 36.113 },
      { name: 'Bahati', latitude: -0.188, longitude: 36.136 },
    ],
  },
  {
    id: 'nakuru-12',
    cityId: 'nakuru',
    number: '12',
    from: 'Nakuru CBD',
    to: 'Egerton University',
    corridor: 'Njoro Road',
    saccos: ['Njoro Sacco', 'Egerton Shuttle'],
    vehicle: '14-seater matatu',
    distanceKm: 21.8,
    durationMin: 45,
    operatingHours: '05:30 – 21:30',
    frequencyMin: 8,
    offPeakFare: { min: 70, max: 90 },
    peakFare: { min: 100, max: 150 },
    color: '#dc2626',
    notes: 'Student route: extremely busy at the start and end of Egerton semesters.',
    stages: [
      { name: 'Nakuru CBD', latitude: -0.283, longitude: 36.066 },
      { name: 'Kaptembwo', latitude: -0.296, longitude: 36.041 },
      { name: 'Njoro Town', latitude: -0.332, longitude: 35.935 },
      { name: 'Egerton University', latitude: -0.369, longitude: 35.933 },
    ],
  },

  // ---------------------------------------------------------------- Eldoret
  {
    id: 'eldoret-1',
    cityId: 'eldoret',
    number: '1',
    from: 'Uganda Road Stage',
    to: 'Langas',
    corridor: 'Kisumu Road',
    saccos: ['Langas Sacco', 'Highlands Shuttle'],
    vehicle: '14-seater matatu',
    distanceKm: 5.6,
    durationMin: 20,
    operatingHours: '05:30 – 22:00',
    frequencyMin: 4,
    offPeakFare: { min: 30, max: 50 },
    peakFare: { min: 50, max: 70 },
    color: '#16a34a',
    notes: 'Busiest Eldoret estate route. Flat fare most of the day.',
    stages: [
      { name: 'Uganda Road Stage', latitude: 0.5143, longitude: 35.2698 },
      { name: 'West Indies', latitude: 0.508, longitude: 35.265 },
      { name: 'Langas', latitude: 0.489, longitude: 35.256 },
    ],
  },
  {
    id: 'eldoret-3',
    cityId: 'eldoret',
    number: '3',
    from: 'Uganda Road Stage',
    to: 'Huruma',
    corridor: 'Kamukunji',
    saccos: ['Huruma Sacco'],
    vehicle: '14-seater matatu',
    distanceKm: 4.4,
    durationMin: 16,
    operatingHours: '05:30 – 22:00',
    frequencyMin: 5,
    offPeakFare: { min: 30, max: 40 },
    peakFare: { min: 50, max: 70 },
    color: '#0ea5e9',
    notes: 'Passes Eldoret market, so luggage space is often limited.',
    stages: [
      { name: 'Uganda Road Stage', latitude: 0.5143, longitude: 35.2698 },
      { name: 'Kamukunji', latitude: 0.523, longitude: 35.279 },
      { name: 'Huruma', latitude: 0.531, longitude: 35.288 },
    ],
  },
  {
    id: 'eldoret-5',
    cityId: 'eldoret',
    number: '5',
    from: 'Uganda Road Stage',
    to: 'Kapsoya',
    corridor: 'Elgon View',
    saccos: ['Kapsoya Sacco', 'Elgon View Shuttle'],
    vehicle: '14-seater matatu',
    distanceKm: 5.0,
    durationMin: 18,
    operatingHours: '06:00 – 21:30',
    frequencyMin: 6,
    offPeakFare: { min: 30, max: 50 },
    peakFare: { min: 50, max: 70 },
    color: '#f97316',
    notes: 'Quieter residential route serving Elgon View and Kapsoya.',
    stages: [
      { name: 'Uganda Road Stage', latitude: 0.5143, longitude: 35.2698 },
      { name: 'Elgon View', latitude: 0.517, longitude: 35.287 },
      { name: 'Kapsoya', latitude: 0.525, longitude: 35.305 },
    ],
  },
  {
    id: 'eldoret-7',
    cityId: 'eldoret',
    number: '7',
    from: 'Uganda Road Stage',
    to: 'Maili Nne',
    corridor: 'Kitale Road',
    saccos: ['Annex Sacco', 'Maili Nne Travellers'],
    vehicle: '25-seater matatu',
    distanceKm: 9.8,
    durationMin: 26,
    operatingHours: '05:30 – 21:30',
    frequencyMin: 7,
    offPeakFare: { min: 40, max: 60 },
    peakFare: { min: 70, max: 90 },
    color: '#7c3aed',
    notes: 'Serves Moi University Annex campus and the Kitale highway estates.',
    stages: [
      { name: 'Uganda Road Stage', latitude: 0.5143, longitude: 35.2698 },
      { name: 'Annex', latitude: 0.558, longitude: 35.3 },
      { name: 'Maili Nne', latitude: 0.573, longitude: 35.326 },
    ],
  },

  // ---------------------------------------------------------------- Thika
  {
    id: 'thika-1',
    cityId: 'thika',
    number: '1',
    from: 'Thika Town Stage',
    to: 'Makongeni',
    corridor: 'Garissa Road',
    saccos: ['Makongeni Sacco'],
    vehicle: '14-seater matatu',
    distanceKm: 3.8,
    durationMin: 15,
    operatingHours: '05:30 – 22:30',
    frequencyMin: 3,
    offPeakFare: { min: 30, max: 40 },
    peakFare: { min: 50, max: 70 },
    color: '#16a34a',
    notes: 'Serves the industrial estates, so shift changes drive the peaks.',
    stages: [
      { name: 'Thika Town Stage', latitude: -1.0388, longitude: 37.0834 },
      { name: 'Section 9', latitude: -1.043, longitude: 37.087 },
      { name: 'Makongeni', latitude: -1.053, longitude: 37.091 },
    ],
  },
  {
    id: 'thika-2',
    cityId: 'thika',
    number: '2',
    from: 'Thika Town Stage',
    to: 'Landless',
    corridor: 'Kiganjo',
    saccos: ['Kiganjo Sacco', 'Landless Travellers'],
    vehicle: '14-seater matatu',
    distanceKm: 6.2,
    durationMin: 20,
    operatingHours: '05:30 – 22:00',
    frequencyMin: 5,
    offPeakFare: { min: 30, max: 50 },
    peakFare: { min: 50, max: 80 },
    color: '#0ea5e9',
    notes: 'Rough sections around Kiganjo slow the route after heavy rain.',
    stages: [
      { name: 'Thika Town Stage', latitude: -1.0388, longitude: 37.0834 },
      { name: 'Kiganjo', latitude: -1.029, longitude: 37.062 },
      { name: 'Landless', latitude: -1.011, longitude: 37.048 },
    ],
  },
  {
    id: 'thika-3',
    cityId: 'thika',
    number: '3',
    from: 'Thika Town Stage',
    to: 'Ngoingwa',
    corridor: 'Ngoingwa',
    saccos: ['Ngoingwa Sacco'],
    vehicle: '14-seater matatu',
    distanceKm: 4.1,
    durationMin: 16,
    operatingHours: '06:00 – 21:30',
    frequencyMin: 6,
    offPeakFare: { min: 30, max: 40 },
    peakFare: { min: 50, max: 60 },
    color: '#f97316',
    notes: 'Short estate hop; tuk tuks compete on the same stages.',
    stages: [
      { name: 'Thika Town Stage', latitude: -1.0388, longitude: 37.0834 },
      { name: 'Kisii Ndogo', latitude: -1.032, longitude: 37.094 },
      { name: 'Ngoingwa', latitude: -1.025, longitude: 37.098 },
    ],
  },
  {
    id: 'thika-237',
    cityId: 'thika',
    number: '237',
    from: 'Thika Town Stage',
    to: 'Nairobi Tea Room',
    corridor: 'Thika Superhighway',
    saccos: ['Super Metro', 'Kenya Mpya', 'Thika Road Sacco'],
    vehicle: '33-seater bus',
    distanceKm: 44.6,
    durationMin: 75,
    operatingHours: '04:30 – 23:00',
    frequencyMin: 4,
    offPeakFare: { min: 100, max: 150 },
    peakFare: { min: 200, max: 300 },
    color: '#dc2626',
    notes: 'Heaviest commuter corridor in the country. Fares climb steeply after 17:00.',
    stages: [
      { name: 'Thika Town Stage', latitude: -1.0388, longitude: 37.0834 },
      { name: 'Juja', latitude: -1.102, longitude: 37.013, landmark: 'JKUAT' },
      { name: 'Ruiru', latitude: -1.145, longitude: 36.96 },
      { name: 'Githurai 45', latitude: -1.193, longitude: 36.92 },
      { name: 'Roysambu', latitude: -1.22, longitude: 36.888 },
      { name: 'Nairobi Tea Room', latitude: -1.283, longitude: 36.828 },
    ],
  },

  // ---------------------------------------------------------------- Nyeri
  {
    id: 'nyeri-1',
    cityId: 'nyeri',
    number: '1',
    from: 'Nyeri Town Stage',
    to: 'Kamakwa',
    corridor: 'Kamakwa Road',
    saccos: ['Kamakwa Sacco'],
    vehicle: '14-seater matatu',
    distanceKm: 3.4,
    durationMin: 14,
    operatingHours: '06:00 – 21:00',
    frequencyMin: 5,
    offPeakFare: { min: 30, max: 40 },
    peakFare: { min: 50, max: 60 },
    color: '#16a34a',
    notes: 'Frequent short hop serving Kamakwa market traders.',
    stages: [
      { name: 'Nyeri Town Stage', latitude: -0.42, longitude: 36.9476 },
      { name: 'Kamakwa', latitude: -0.413, longitude: 36.964 },
    ],
  },
  {
    id: 'nyeri-2',
    cityId: 'nyeri',
    number: '2',
    from: 'Nyeri Town Stage',
    to: 'Witemere',
    corridor: 'Kingongo',
    saccos: ['Kingongo Sacco', 'Witemere Travellers'],
    vehicle: '14-seater matatu',
    distanceKm: 4.2,
    durationMin: 16,
    operatingHours: '06:00 – 21:00',
    frequencyMin: 7,
    offPeakFare: { min: 30, max: 40 },
    peakFare: { min: 50, max: 60 },
    color: '#0ea5e9',
    notes: 'Steep climb into Kingongo; older vehicles are slow on this stretch.',
    stages: [
      { name: 'Nyeri Town Stage', latitude: -0.42, longitude: 36.9476 },
      { name: 'Kingongo', latitude: -0.423, longitude: 36.93 },
      { name: 'Witemere', latitude: -0.418, longitude: 36.925 },
    ],
  },
  {
    id: 'nyeri-3',
    cityId: 'nyeri',
    number: '3',
    from: 'Nyeri Town Stage',
    to: 'Kiganjo',
    corridor: "Ruring'u / Kiganjo",
    saccos: ["Ruring'u Sacco", 'Kiganjo Shuttle'],
    vehicle: '25-seater matatu',
    distanceKm: 8.6,
    durationMin: 24,
    operatingHours: '05:45 – 21:00',
    frequencyMin: 8,
    offPeakFare: { min: 40, max: 60 },
    peakFare: { min: 70, max: 90 },
    color: '#f97316',
    notes: 'Serves the police training college; heavy on pass-out weekends.',
    stages: [
      { name: 'Nyeri Town Stage', latitude: -0.42, longitude: 36.9476 },
      { name: "Ruring'u", latitude: -0.436, longitude: 36.942 },
      { name: 'Kiganjo', latitude: -0.468, longitude: 36.999 },
    ],
  },
  {
    id: 'nyeri-5',
    cityId: 'nyeri',
    number: '5',
    from: 'Nyeri Town Stage',
    to: 'Mweiga',
    corridor: 'Nyahururu Road',
    saccos: ['Mweiga Sacco', 'Aberdare Shuttle'],
    vehicle: '25-seater matatu',
    distanceKm: 16.4,
    durationMin: 35,
    operatingHours: '06:00 – 20:00',
    frequencyMin: 12,
    offPeakFare: { min: 60, max: 80 },
    peakFare: { min: 100, max: 130 },
    color: '#7c3aed',
    notes: 'Gateway route for Aberdare National Park visitors.',
    stages: [
      { name: 'Nyeri Town Stage', latitude: -0.42, longitude: 36.9476 },
      { name: 'Kabiruini', latitude: -0.405, longitude: 36.93 },
      { name: 'Mweiga', latitude: -0.316, longitude: 36.873 },
    ],
  },

  // ---------------------------------------------------------------- Machakos
  {
    id: 'machakos-1',
    cityId: 'machakos',
    number: '1',
    from: 'Machakos Town Stage',
    to: 'Mumbuni',
    corridor: 'Mumbuni Road',
    saccos: ['Mumbuni Sacco'],
    vehicle: '14-seater matatu',
    distanceKm: 3.2,
    durationMin: 13,
    operatingHours: '06:00 – 21:00',
    frequencyMin: 5,
    offPeakFare: { min: 30, max: 40 },
    peakFare: { min: 50, max: 60 },
    color: '#16a34a',
    notes: 'Short town route serving Machakos University students.',
    stages: [
      { name: 'Machakos Town Stage', latitude: -1.5177, longitude: 37.2634 },
      { name: 'Mumbuni', latitude: -1.523, longitude: 37.276 },
    ],
  },
  {
    id: 'machakos-2',
    cityId: 'machakos',
    number: '2',
    from: 'Machakos Town Stage',
    to: 'Kathiani',
    corridor: 'Kathiani Road',
    saccos: ['Kathiani Sacco', 'Katoloni Travellers'],
    vehicle: '14-seater matatu',
    distanceKm: 12.6,
    durationMin: 32,
    operatingHours: '06:00 – 20:30',
    frequencyMin: 10,
    offPeakFare: { min: 50, max: 70 },
    peakFare: { min: 80, max: 110 },
    color: '#0ea5e9',
    notes: 'Winding hill route; expect longer waits outside market days.',
    stages: [
      { name: 'Machakos Town Stage', latitude: -1.5177, longitude: 37.2634 },
      { name: 'Katoloni', latitude: -1.493, longitude: 37.308 },
      { name: 'Kathiani', latitude: -1.453, longitude: 37.326 },
    ],
  },
  {
    id: 'machakos-3',
    cityId: 'machakos',
    number: '3',
    from: 'Machakos Town Stage',
    to: 'Athi River',
    corridor: 'Machakos Turnoff / Mombasa Road',
    saccos: ['Athi River Sacco', 'Kyumbi Shuttle', 'Machakos Kenya Mpya'],
    vehicle: '33-seater bus',
    distanceKm: 35.4,
    durationMin: 55,
    operatingHours: '05:00 – 22:00',
    frequencyMin: 6,
    offPeakFare: { min: 100, max: 130 },
    peakFare: { min: 150, max: 200 },
    color: '#dc2626',
    notes: 'Main link to Mombasa Road and onward matatus to Nairobi.',
    stages: [
      { name: 'Machakos Town Stage', latitude: -1.5177, longitude: 37.2634 },
      { name: 'Kyumbi', latitude: -1.456, longitude: 37.12, landmark: 'Machakos Turnoff' },
      { name: 'Athi River', latitude: -1.456, longitude: 36.978 },
    ],
  },
  {
    id: 'machakos-14',
    cityId: 'machakos',
    number: '14',
    from: 'Machakos Town Stage',
    to: 'Wamunyu',
    corridor: 'Kitui Road',
    saccos: ['Wamunyu Sacco'],
    vehicle: '25-seater matatu',
    distanceKm: 26.8,
    durationMin: 50,
    operatingHours: '06:00 – 20:00',
    frequencyMin: 15,
    offPeakFare: { min: 80, max: 100 },
    peakFare: { min: 120, max: 160 },
    color: '#f97316',
    notes: 'Serves the Wamunyu woodcarving cooperatives on the Kitui road.',
    stages: [
      { name: 'Machakos Town Stage', latitude: -1.5177, longitude: 37.2634 },
      { name: 'Kalama', latitude: -1.49, longitude: 37.33 },
      { name: 'Wamunyu', latitude: -1.438, longitude: 37.452 },
    ],
  },
];

export function getCity(cityId: string | undefined) {
  return CITIES.find((city) => city.id === cityId);
}

export function getRoute(routeId: string | undefined) {
  return ROUTES.find((route) => route.id === routeId);
}

export function getRoutesByCity(cityId: string) {
  return ROUTES.filter((route) => route.cityId === cityId);
}

export function countRoutes(cityId: string) {
  return getRoutesByCity(cityId).length;
}

export function countStages(cityId: string) {
  return getRoutesByCity(cityId).reduce((total, route) => total + route.stages.length, 0);
}

export function getRoutes(routeIds: string[]) {
  return routeIds
    .map((routeId) => getRoute(routeId))
    .filter((route): route is MatatuRoute => Boolean(route));
}

function matches(route: MatatuRoute, needle: string) {
  if (route.number.toLowerCase().includes(needle)) return true;
  if (route.from.toLowerCase().includes(needle)) return true;
  if (route.to.toLowerCase().includes(needle)) return true;
  if (route.corridor.toLowerCase().includes(needle)) return true;
  if (route.saccos.some((sacco) => sacco.toLowerCase().includes(needle))) return true;
  if (route.stages.some((stage) => stage.name.toLowerCase().includes(needle))) return true;
  return getCity(route.cityId)?.name.toLowerCase().includes(needle) ?? false;
}

export function searchRoutes(query: string, cityId?: string) {
  const needle = query.trim().toLowerCase();
  const scoped = cityId ? getRoutesByCity(cityId) : ROUTES;
  if (!needle) return scoped;
  return scoped.filter((route) => matches(route, needle));
}
